import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import { Col, Container, Row } from "react-bootstrap";
import Sidebar from "@/components/Layouts/Sidebar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{width:"100%",height:"100%" ,}}>
        <Container fluid style={{height:"100vh", }}>
          <Row style={{paddingLeft:"10px"}}>
            <Col className="box-container" md={2} style={{marginTop:"10px", height:"96vh", paddingTop:'20px', overflow:"hidden", overflowY:'scroll'}}><Sidebar /></Col>
            <Col md={10}>{children}</Col>
          </Row>
        </Container>
      </body>
    </html>
  );
}



{/* <body style={{width:"100%", }}>
        <div className="d-flex flex-column flex-md-row " style={{ minHeight: 'calc(100vh - 2rem)', backgroundColor: "#F8F9FA"  }}>
         
          <Sidebar />
          
          <div className="flex-grow-1 d-flex flex-column">
            <div className="flex-grow-1 bg-light p-4 overflow-auto" style={{ border: "1px solid blue", backgroundColor: "white" }}>
              {children}
            </div>
          </div>
        </div>
      </body> */}
